import SessionProviderWrapper from "@/components/providers";
import { modern, retro } from "@/fonts";
import "@/global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auto test AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${retro.variable} ${modern.variable}`}>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
